months = [{"id": 1, "name": "January"},
          {"id": 2, "name": "February"},
          {"id": 3, "name": "March"},
          {"id": 4, "name": "Abril"},
          {"id": 5, "name": "May"},
          {"id": 6, "name": "June"},
          {"id": 7, "name": "July"},
          {"id": 8, "name": "August"},
          {"id": 9, "name": "September"},
          {"id": 10, "name": "October"},
          {"id": 11, "name": "November"},
          {"id": 12, "name": "December"}]

messages = {0: ["", "danger"],
            1: ["You do not have permissions", "warning"],
            2: ["Record was inserted successfully", "success"],
            3: ["Record was updated", "success"],
            4: ["Record was deleted", "success"],
            5: ["Report was downloaded", "success"],
            6: ["Login was successful", "success"],
            7: ["Email or password is not valid", "warning"],
            8: ["Record was inserted and uploaded successfully", "success"],
            9: ["Your password was changed successfully", "success"],
            10: ["Current password is not valid", "warning"],
            11: ["The record already exists", "warning"]}

pages = {"database": {'index': 'database.index',
                      'create': 'database.create',
                      'edit': 'database.edit',
                      'delete': 'database.delete'},
         "file": {'index': 'file.index',
                  'create': 'file.create',
                  'edit': 'file.edit',
                  'delete': 'file.delete'},
         "inventory": {'index': 'inventory.index',
                       'create': 'inventory.create',
                       'delete': 'inventory.delete',
                       'download': 'inventory.download'},
         "page": {'index': 'page.index',
                  'create': 'page.create',
                  'edit': 'page.edit',
                  'delete': 'page.delete'},
         "permission": {'index': 'role.index',
                        'edit': 'permission.edit'},
         "report": {'index': 'report.index',
                    'create': 'report.create',
                    'edit': 'report.edit',
                    'delete': 'report.delete',
                    'download': 'report.download'},
         "role": {'index': 'role.index',
                  'create': 'role.create',
                  'edit': 'role.edit',
                  'delete': 'role.delete'},
         "upload": {'index': 'upload.index',
                    'create': 'upload.create',
                    'delete': 'upload.delete'},
         "user": {'index': 'user.index',
                  'create': 'user.create',
                  'edit': 'user.edit',
                  'delete': 'user.delete',
                  'login': 'user.login',
                  'change_password': 'user.change_password'},
         }

routes = {"database": {'index': '/database',
                       'create': '/database/create',
                       'edit': '/database/edit/<int:id>',
                       'delete': '/database/delete/<int:id>'},
          "file": {'index': '/file',
                   'create': '/file/create',
                   'edit': '/file/edit/<int:id>',
                   'delete': '/file/delete/<int:id>'},
          "inventory": {'index': '/inventory',
                        'create': '/inventory/create',
                        'delete': '/inventory/delete/<int:id>',
                        'download': '/inventory/download/<int:id>'},
          "page": {'index': '/page',
                   'create': '/page/create',
                   'edit': '/page/edit/<int:id>',
                   'delete': '/page/delete/<int:id>'},
          "permission": {'edit': '/permission/edit/<int:id>'},
          "report": {'index': '/report',
                     'create': '/report/create',
                     'edit': '/report/edit/<int:id>',
                     'delete': '/report/delete/<int:id>',
                     'download': '/report/download/<int:id>'},
          "role": {'index': '/role',
                   'create': '/role/create',
                   'edit': '/role/edit/<int:id>',
                   'delete': '/role/delete/<int:id>'},
          "upload": {'index': '/upload',
                     'create': '/upload/create',
                     'delete': '/upload/delete/<int:id>'},
          "user": {'index': '/user',
                   'create': '/user/create',
                   'edit': '/user/edit/<int:id>',
                   'delete': '/user/delete/<int:id>',
                   'login': '/user/login',
                   'change_password': '/user/change_password'},
          }

templates = {"database": {'index': '/database/index.html',
                          'create': '/database/create.html',
                          'edit': '/database/create.html'},
             "file": {'index': '/file/index.html',
                      'create': '/file/create.html',
                      'edit': '/file/create.html'},
             "inventory": {'index': '/inventory/index.html',
                           'create': '/inventory/create.html',
                           'edit': '/inventory/create.html'},
             "page": {'index': '/page/index.html',
                      'create': '/page/create.html',
                      'edit': '/page/create.html'},
             "permission": {'edit': '/permission/edit.html'},
             "report": {'index': '/report/index.html',
                        'create': '/report/create.html',
                        'edit': '/report/create.html'},
             "role": {'index': '/role/index.html',
                      'create': '/role/create.html',
                      'edit': '/role/create.html'},
             "upload": {'index': '/upload/index.html',
                        'create': '/upload/create.html'},
             "user": {'index': '/user/index.html',
                      'create': '/user/create.html',
                      'edit': '/user/create.html',
                      'login': '/user/login.html',
                      'change_password': '/user/change_password.html'},
             }

route_page = [['database.index', 'Can View Databases'],
              ['database.create', 'Can Create Databases'],
              ['database.edit', 'Can Edit Databases'],
              ['database.delete', 'Can Delete Databases'],
              ['file.index', 'Can View Files'],
              ['file.create', 'Can Create Files'],
              ['file.edit', 'Can Edit Files'],
              ['file.delete', 'Can Delete Files'],
              ['inventory.index', 'Can View Inventories'],
              ['inventory.create', 'Can Create Inventories'],
              ['inventory.delete', 'Can Delete Inventories'],
              ['inventory.download', 'Can Download Inventories'],
              ['page.index', 'Can View Pages'],
          ['page.create', 'Can Create Pages'],
          ['page.edit', 'Can Edit Pages'],
          ['page.delete', 'Can Delete Pages'],
          ['report.index', 'Can View Reports'],
          ['report.create', 'Can Create Reports'],
          ['report.edit', 'Can Edit Reports'],
          ['report.delete', 'Can Delete Reports'],
          ['report.download', 'Can Download Reports'],
          ['role.index', 'Can View Roles'],
          ['role.create', 'Can Create Roles'],
          ['role.edit', 'Can Edit Roles'],
          ['role.delete', 'Can Delete Roles'],
          ['permission.edit', 'Can Set Role Permissions'],
          ['upload.index', 'Can View uploaded Files'],
          ['upload.create', 'Can Upload Files'],
          ['upload.delete', 'Can Delete Uploaded Files'],
          ['user.index', 'Can View Users'],
          ['user.create', 'Can Create Users'],
          ['user.edit', 'Can Edit Users'],
          ['user.delete', 'Can Delete Users'],
]
